language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script: 
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - cd tests
  - phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ../build/logs/clover.xml

notifications:
  email:
    - purwantoyudi42@gmail.com
